### ISSUE TITLE
CT the right hand side value must be a number

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-ac-virtual-lab#2] opened 2021-04-19 15:32 UTC
```
circuit-construction-kit-ac-virtual-lab : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618822750047/circuit-construction-kit-ac-virtual-lab/circuit-construction-kit-ac-virtual-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-ac-virtual-lab%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1618822750047%22%2C%22timestamp%22%3A1618833602001%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: the right-hand-side-value must be a number
Error: Assertion failed: the right-hand-side-value must be a number
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618822750047/assert/js/assert.js:25:13)
at ModifiedNodalAnalysisCircuit.solve (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618822750047/circuit-construction-kit-common/js/model/ModifiedNodalAnalysisCircuit.js:352:17)
at DynamicCircuit.solvePropagate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618822750047/circuit-construction-kit-common/js/model/DynamicCircuit.js:150:36)
at DynamicState.update (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618822750047/circuit-construction-kit-common/js/model/DynamicCircuit.js:398:41)
at Object.update (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618822750047/circuit-construction-kit-common/js/model/DynamicCircuit.js:162:30)
at TimestepSubdivisions.errorAcceptable (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618822750047/circuit-construction-kit-common/js/model/TimestepSubdivisions.js:81:25)
at TimestepSubdivisions.getTimestep (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618822750047/circuit-construction-kit-common/js/model/TimestepSubdivisions.js:65:20)
at TimestepSubdivisions.stepInTimeWithHistory (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618822750047/circuit-construction-kit-common/js/model/TimestepSubdivisions.js:41:32)
at DynamicCircuit.solveWithSubdivisions (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618822750047/circuit-construction-kit-common/js/model/DynamicCircuit.js:167:36)
at Function.solveModifiedNodalAnalysis (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618822750047/circuit-construction-kit-common/js/model/ModifiedNodalAnalysisAdapter.js:179:40)
id: Bayes Chrome
Snapshot from 4/19/2021, 2:59:10 AM

----------------------------------

circuit-construction-kit-ac-virtual-lab : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618822750047/circuit-construction-kit-ac-virtual-lab/circuit-construction-kit-ac-virtual-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-ac-virtual-lab%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1618822750047%22%2C%22timestamp%22%3A1618840433606%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: the right-hand-side-value must be a number
Error: Assertion failed: the right-hand-side-value must be a number
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618822750047/assert/js/assert.js:25:13)
at ModifiedNodalAnalysisCircuit.solve (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618822750047/circuit-construction-kit-common/js/model/ModifiedNodalAnalysisCircuit.js:352:17)
at DynamicCircuit.solvePropagate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618822750047/circuit-construction-kit-common/js/model/DynamicCircuit.js:150:36)
at DynamicState.update (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618822750047/circuit-construction-kit-common/js/model/DynamicCircuit.js:398:41)
at Object.update (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618822750047/circuit-construction-kit-common/js/model/DynamicCircuit.js:162:30)
at TimestepSubdivisions.errorAcceptable (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618822750047/circuit-construction-kit-common/js/model/TimestepSubdivisions.js:83:26)
at TimestepSubdivisions.getTimestep (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618822750047/circuit-construction-kit-common/js/model/TimestepSubdivisions.js:65:20)
at TimestepSubdivisions.stepInTimeWithHistory (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618822750047/circuit-construction-kit-common/js/model/TimestepSubdivisions.js:41:32)
at DynamicCircuit.solveWithSubdivisions (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618822750047/circuit-construction-kit-common/js/model/DynamicCircuit.js:167:36)
at Function.solveModifiedNodalAnalysis (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618822750047/circuit-construction-kit-common/js/model/ModifiedNodalAnalysisAdapter.js:179:40)
id: Bayes Chrome
Snapshot from 4/19/2021, 2:59:10 AM
```

**Comment by samreid** [comment] 2021-04-20 19:38
Duplicate of https://github.com/phetsims/circuit-construction-kit-ac/issues/26

**Closed as completed by samreid** 2021-04-20 19:38 UTC
Labels: type:automated-testing
