### ISSUE TITLE
CT mnaVoltageDrop out of range

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-ac-virtual-lab#3] opened 2021-07-26 14:50 UTC
```
circuit-construction-kit-ac-virtual-lab : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627278142889/circuit-construction-kit-ac-virtual-lab/circuit-construction-kit-ac-virtual-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-ac-virtual-lab%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1627278142889%22%2C%22timestamp%22%3A1627291747338%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: mnaVoltageDrop out of range
Error: Assertion failed: mnaVoltageDrop out of range
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627278142889/assert/js/assert.js:25:13)
at InductorAdapter.applySolution (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627278142889/circuit-construction-kit-common/js/model/ModifiedNodalAnalysisAdapter.js:142:15)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627278142889/circuit-construction-kit-common/js/model/ModifiedNodalAnalysisAdapter.js:247:66
at Array.forEach (<anonymous>)
at Function.solveModifiedNodalAnalysis (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627278142889/circuit-construction-kit-common/js/model/ModifiedNodalAnalysisAdapter.js:247:22)
at Circuit.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627278142889/circuit-construction-kit-common/js/model/Circuit.js:912:36)
at CircuitConstructionKitModel.stepOnce (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627278142889/circuit-construction-kit-common/js/model/CircuitConstructionKitModel.js:218:64)
at CircuitConstructionKitModel.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627278142889/circuit-construction-kit-common/js/model/CircuitConstructionKitModel.js:244:12)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627278142889/joist/js/Sim.js:307:22
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627278142889/axon/js/Action.js:227:18)
id: Bayes Chrome
Snapshot from 7/25/2021, 11:42:22 PM
```

**Comment by samreid** [comment] 2021-07-28 05:43
Closing as a duplicate of https://github.com/phetsims/circuit-construction-kit-common/issues/711

**Closed as completed by samreid** 2021-07-28 05:43 UTC
Labels: type:duplicate, type:automated-testing
